use[GROUPWAREDB]
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[T_GROUPSTAFF]') AND type in (N'U'))
DROP TABLE [dbo].[T_GROUPSTAFF]
GO

CREATE TABLE [dbo].[T_GROUPSTAFF](
	[staf_cd] [int] NOT NULL,
	[group_cd] [int] NOT NULL,
	[update_user] [varchar](10) NOT NULL,
	[update_date] [datetime2](7) NOT NULL,
 CONSTRAINT [PK_T_GROUPSTAFF] PRIMARY KEY CLUSTERED 
(
	[staf_cd] ASC,
	[group_cd] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
