use[GROUPWAREDB]
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[T_INFO_FILE]') AND type in (N'U'))
DROP TABLE [dbo].[T_INFO_FILE]
GO

CREATE TABLE [dbo].[T_INFO_FILE](
	[file_no] [int] NOT NULL,
	[info_cd] [int] NOT NULL,
	[fileName] [nvarchar](100) NOT NULL,
	[fullPath] [nvarchar](100) NOT NULL,
	[update_user] [varchar](10) NOT NULL,
	[update_date] [datetime2](7) NOT NULL,
 CONSTRAINT [PK_T_INFO_FILE_1] PRIMARY KEY CLUSTERED 
(
	[file_no] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
