use[GROUPWAREDB]
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[T_MEMO_READ]') AND type in (N'U'))
DROP TABLE [dbo].[T_MEMO_READ]
GO

CREATE TABLE [dbo].[T_MEMO_READ](
	[memo_no] [int] NOT NULL,
	[staff_cd] [int] NOT NULL,
	[read_flag] [bit] NOT NULL,
	[update_user] [varchar](10) NOT NULL,
	[update_date] [datetime2](7) NOT NULL
 CONSTRAINT [PK_T_MEMO_READ] PRIMARY KEY CLUSTERED 
(
	[memo_no] ASC,
	[staff_cd] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

