use[GROUPWAREDB]
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[T_NO]') AND type in (N'U'))
DROP TABLE [dbo].[T_NO]
GO

CREATE TABLE [dbo].[T_NO](
	[data_type] [int] NOT NULL,
	[no] [int] NOT NULL,
 CONSTRAINT [PK_T_NO] PRIMARY KEY CLUSTERED 
(
	[data_type] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[T_NO] ADD  CONSTRAINT [DF_T_NO_no]  DEFAULT ((1)) FOR [no]
GO
