USE [GROUPWAREDB]
GO

/****** Object: Table [dbo].[T_SCHEDULEPEOPLE] Script Date: 1/17/2024 6:29:55 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

DROP TABLE [dbo].[T_SCHEDULEPEOPLE];


GO
CREATE TABLE [dbo].[T_SCHEDULEPEOPLE] (
    [schedule_no] INT NOT NULL,
    [staf_cd]     INT NOT NULL
CONSTRAINT [PK_T_SCHEDULEPEOPLE] PRIMARY KEY CLUSTERED 
(
	[schedule_no] ASC,
	[staf_cd] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


