USE [GROUPWAREDB]
GO

/****** Object: Table [dbo].[T_SCHEDULEPLACE] Script Date: 1/17/2024 6:30:37 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

DROP TABLE [dbo].[T_SCHEDULEPLACE];


GO
CREATE TABLE [dbo].[T_SCHEDULEPLACE] (
    [schedule_no] INT NOT NULL,
    [place_cd]    INT NOT NULL
CONSTRAINT [PK_T_SCHEDULEPLACE] PRIMARY KEY CLUSTERED 
(
	[schedule_no] ASC,
	[place_cd] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


